image: gitpod/workspace-dotnet

tasks:
  - init: >
      dotnet tool install paket -g && dotnet tool install fake-cli -g


vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.0.6:jY7uvWaRUfDGixUAwJWzOg==