image: gitpod/workspace-dotnet

tasks:
  - init: >
      dotnet tool install paket --tool-path /workspace/.dotnet/tools -g
      dotnet tool install fake-cli --tool-path /workspace/.dotnet/tools -g
      export PATH=/workspace/.dotnet/tools:$PATH


vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.0.6:jY7uvWaRUfDGixUAwJWzOg==