image: gitpod/workspace-dotnet

tasks:
  - init: dotnet tool install --tool-path .paket Paket && export PATH=.paket:$PATH

vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.0.6:jY7uvWaRUfDGixUAwJWzOg==