baseURL = "https://moiraesoftware.github.io/myriad/"
languageCode = "en-us"
title = "Myriad"
theme = "hugo-theme-relearn"
disableLandingPageButton = true

# For search functionality  
[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.main]]
    name = "GitHub"
    weight = 60
    url = "https://github.com/MoiraeSoftware/myriad"
    pre = "<i class='fab fa-github'></i>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
