baseURL = "https://moiraesoftware.github.io/myriad/"
languageCode = "en-us"
title = "Myriad"
theme = "docsy"
disableLandingPageButton = true
contentDir = "content/"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Lanugages]
[Lanugages.en]

landingPageURL = "/en"
landingPageName = "<i class='fas fa-shome'></i> Redirect to Homeddd"

[Lanugages.fr]

landingPageURL = "/fr"
landingPageName = "<i class='fas fa-home'></i> Accueil"

[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/MoiraeSoftware/myriad"
    pre = "<i class='fab fa-github'></i>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true