baseURL = "http://example.org/"
languageCode = "en-us"
title = "Myriad"
theme = "hugo-theme-relearn"
disableLandingPageButton = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Lanugages]
[Lanugages.en]

landingPageURL = "/en"
landingPageName = "<i class='fas fa-shome'></i> Redirect to Homeddd"

[Lanugages.fr]

landingPageURL = "/fr"
landingPageName = "<i class='fas fa-home'></i> Accueil"
