baseURL = "https://moiraesoftware.github.io/myriad/"
languageCode = "en-us"
title = "Myriad"
theme = "hugo-theme-relearn"
disableLandingPageButton = true

# For search functionality  
[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub"
weight = 60
url = "https://github.com/MoiraeSoftware/myriad"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
