name: Release docs

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core 2.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
        
    - name: Use .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        
    # Not specifying a version will attempt to install via global.json
    - name: Use .NET Core global.json
      uses: actions/setup-dotnet@v1
      
    - name: Restore tools
      run: dotnet tool restore
      
    - name: Run Fornax
      run: dotnet fake build -t Docs
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_public
        publish_branch: gh-pages
        force_orphan: true
        
        


